import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import { copy } from "esbuild-plugin-copy";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	watch: !prod,
	target: 'es2018',
	plugins: [
		copy({
			assets: {
				from: ['main.js'],
				to: ['./build/main.js'],
			},
		}),
		copy({
			assets: {
				from: ['manifest.json'],
				to: ['./build/manifest.json'],
			},
		}),
		copy({
			assets: {
				from: ['styles.css'],
				to: ['./build/styles.css'],
			},
		})
	],
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
}).catch(() => process.exit(1));
